# Generated by Django 2.1.5 on 2019-04-15 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pus', '0002_employee_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='age',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
